version: '3.8'

services:
  gau-phim-backend:
    image: iamqbao/gau_phim_backend:latest
    container_name: gau-phim-backend
    restart:
      always
    volumes:
      - .env.flix:/gau_phim/.env.flix
    networks:
      app-network:
        ipv4_address: 172.18.0.10

networks:
  app-network:
    external: true
