version: '3.8'

services:
  gau-user-service:
    image: iamqbao/gau_user_service:latest
    container_name: gau-user-service
    depends_on:
      - postgres
    volumes:
      - /home/debian/gau/.env:/gau_user/.env
    networks:
      app-network:
        ipv4_address: 172.18.0.2
    environment:
      DATABASE_URL: "postgres://user:password@172.18.0.54:5432/mydb"
      REDIS_URL: "redis://:password@172.18.0.67:6379"

  gau-validation-service:
    image: iamqbao/gau_validation_service:latest
    container_name: gau-validation-service
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - /home/debian/gau/.env:/gau_validation/.env
    networks:
      app-network:
        ipv4_address: 172.18.0.3
    environment:
      DATABASE_URL: "postgres://user:password@172.18.0.54:5432/mydb"
      REDIS_URL: "redis://:password@172.18.0.67:6379"

networks:
  app-network:
    external: true
