version: '3.8'

services:
  gau-user-service:
    image: iamqbao/gau_user_service:latest
    container_name: gau-user-service
    restart: always
    volumes:
      - .env:/gau_user/.env
    networks:
      app-network:
        ipv4_address: 172.18.0.2

  gau-validation-service:
    image: iamqbao/gau_validation_service:latest
    container_name: gau-validation-service
    restart: always
    volumes:
      - .env:/gau_validation/.env
    networks:
      app-network:
        ipv4_address: 172.18.0.3

networks:
  app-network:
    external: true
